name: NPM

on:
  release:
    types:
      - published

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const { readFileSync, writeFileSync } = require('fs');
            const { fileURLToPath } = require('url');
            const { resolve } = require('path');
            const { cwd } = require('process');
            const file = resolve(cwd(), 'package.json');
            const content = JSON.parse(readFileSync(file, 'utf8'));
            content.version = "${{ github.event.release.tag_name }}";
            writeFileSync(file, JSON.stringify(content, null, '    '));

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
