name: NPM

on:
  release:
    types:
      - published

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const { readFileSync, writeFileSync } = require('fs');
            const { fileURLToPath } = require('url');
            const pkgJson = '${{ github.workspace }}/package.json';
            const content = JSON.parse(readFileSync(pkgJson, 'utf8'));
            content.version = "${{ github.event.release.tag_name }}";
            writeFileSync(pkgJson, JSON.stringify(content, null, '    '));

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
